export enum PLAYER_POSITION {
  GK = 'GK',
  CB = 'CB',
  LB = 'LB',
  RB = 'RB',
  CDM = 'CDM',
  CM = 'CM',
  CAM = 'CAM',
  LM = 'LM',
  RM = 'RM',
  LW = 'LW',
  RW = 'RW',
  ST = 'ST',
};

export enum PLAYER_ROLE {
  GOALKEEPER = 'GOALKEEPER',
  DEFENDER = 'DEFENDER',
  MIDFIELDER = 'MIDFIELDER',
  ATTACKER = 'ATTACKER'
};

export const PLAYER_POSITIONS_BY_ROLES: Partial<Record<PLAYER_ROLE, PLAYER_POSITION[]>> = {
  [PLAYER_ROLE.GOALKEEPER]: [PLAYER_POSITION.GK],
  [PLAYER_ROLE.DEFENDER]: [PLAYER_POSITION.CB, PLAYER_POSITION.LB, PLAYER_POSITION.RB],
  [PLAYER_ROLE.MIDFIELDER]: [PLAYER_POSITION.LM, PLAYER_POSITION.CM, PLAYER_POSITION.RM, PLAYER_POSITION.CAM],
  [PLAYER_ROLE.ATTACKER]: [PLAYER_POSITION.LW, PLAYER_POSITION.RW, PLAYER_POSITION.ST],
};
