export enum TABLE_NAMES {
  ENVIRONMENTS = 'environments',
  COUNTRIES = 'countries',
  REGIONS = 'regions',
  TEAMS = 'teams',
  TOURNAMENTS = 'tournaments',
  TEAMS_TOURNAMENTS = 'teams_tournaments',
  PLAYERS = 'players',
  MATCHES = 'matches',
  MATCHE_SCORES = 'match_scores',
  INDICATOR_TYPES = 'indicator_types',
  TEAM_INDICATORS = 'team_indicators',
  PLAYER_INDICATORS = 'player_indicators',
  DIVISIONS = 'divisions',
  TEAMS_PLAYERS = 'teams_players',
  AWARDS = 'awards',
  PLAYERS_AWARDS = 'players_awards',
  PLAYER_PLAYER_INDICATORS = 'players_player_indicators',
};
